/*
 * This source file was generated by the Gradle 'init' task
 */
package MQTT.message;

import java.io.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import MQTT.Message.*;
class MessageTest {
    @Test void validBytes() {
		try{
			Message original = new Message(MessageType.PUBLISH);
			original.setTopic("test/topic");
			original.setPayload("Hello MQTT".getBytes());
			original.setQoS(1);
			original.setPacketId(1234);
			original.setDup(0);
			original.setRetain(1);

			byte[] data = original.getMessageBytes();

			ByteArrayInputStream bais = new ByteArrayInputStream(data);
			DataInputStream dis = new DataInputStream(bais);
			Message parsed = new Message(dis);

			assertEquals(original.getType(), parsed.getType());
			assertEquals(original.getQoS(), parsed.getQoS());
			assertEquals(original.getPacketId(), parsed.getPacketId());
			assertEquals(original.getTopic(), parsed.getTopic());
			assertArrayEquals(original.getPayload(), parsed.getPayload());
			assertEquals(original.getDup(), parsed.getDup());
			assertEquals(original.getRetain(), parsed.getRetain());
		}catch(IOException i){
				
		}
    }
}
